version: '3.8'
services:

    # Redis
    redis:
        build: docker/redis
        container_name: gbs_jwt_redis
        volumes:
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        expose:
            - 6379
        ports:
            - 6379:6379
